package ua.demo.agentlab.api.model;

public enum ApiAssertionType {
    STATUS_CODE_EQUALS,
    JSON_FIELD_EQUALS,
    JSON_FIELD_EXISTS,
    JSON_FIELD_NOT_EMPTY,
    JSON_ARRAY_SIZE_GREATER_THAN,
    SCHEMA_VALID,
    CONTENT_TYPE_JSON,
    HEADER_EQUALS,
    RESPONSE_TIME_UNDER,
    ERROR_MESSAGE_MATCHES,
    AUTH_REQUIRED,
    FORBIDDEN_WITHOUT_ROLE
}
