base.url=${project.base-url}

credentials.valid-user.username=${test.credentials.valid.username}
credentials.valid-user.password=${test.credentials.valid.password}
credentials.invalid-user.username=${test.credentials.invalid.username}
credentials.invalid-user.password=${test.credentials.invalid.password}
credentials.public-user.username=${test.credentials.valid.username}
credentials.public-user.password=${test.credentials.valid.password}

data.home-default.route=${project.route.home}
data.home-default.expectedRouteFragment=${project.route.home}
data.home-default.expectedPageKeyword=login

data.dashboard-default.route=${project.route.authenticated}
data.dashboard-default.expectedRouteFragment=${project.route.authenticated}
data.dashboard-default.expectedPageKeyword=dashboard

data.form-default.route=${project.route.login}
data.form-default.expectedRouteFragment=${project.route.authenticated}
data.form-default.username=${test.credentials.valid.username}
data.form-default.password=${test.credentials.valid.password}
data.form-default.expectedPageKeyword=dashboard

data.login-default.route=${project.route.login}
data.login-default.expectedRouteFragment=${project.route.authenticated}
data.login-default.username=${test.credentials.valid.username}
data.login-default.password=${test.credentials.valid.password}
data.login-default.expectedPageKeyword=dashboard
