base.url=${project.base-url}

credentials.valid-user.username=${test.credentials.valid.username}
credentials.valid-user.password=${test.credentials.valid.password}
credentials.invalid-user.username=${test.credentials.invalid.username}
credentials.invalid-user.password=${test.credentials.invalid.password}
credentials.public-user.username=${test.credentials.valid.username}
credentials.public-user.password=${test.credentials.valid.password}

data.home-default.route=${project.route.home}
data.home-default.expectedRouteFragment=${project.route.home}
data.home-default.expectedListingKeyword=example
data.home-default.query=all
data.home-default.filterValue=all
data.home-default.entityKey=${project.navigation.auth-link-text}
data.home-default.size=default
data.home-default.color=default

data.dashboard-default.route=${project.route.authenticated}
data.dashboard-default.expectedRouteFragment=${project.route.authenticated}
data.dashboard-default.expectedListingKeyword=authenticated
data.dashboard-default.query=all
data.dashboard-default.filterValue=all
data.dashboard-default.entityKey=secure-area
data.dashboard-default.size=default
data.dashboard-default.color=default

data.listing-default.route=${project.route.home}
data.listing-default.expectedRouteFragment=${project.route.home}
data.listing-default.expectedListingKeyword=example
data.listing-default.query=all
data.listing-default.filterValue=all
data.listing-default.entityKey=${project.navigation.auth-link-text}
data.listing-default.size=default
data.listing-default.color=default

data.details-default.route=${project.route.login}
data.details-default.expectedRouteFragment=${project.route.login}
data.details-default.entityKey=${project.navigation.auth-link-text}
data.details-default.size=default
data.details-default.color=default

data.form-default.route=${project.route.login}
data.form-default.expectedRouteFragment=${project.route.authenticated}
data.form-default.query=all
data.form-default.filterValue=all
data.form-default.username=${test.credentials.valid.username}
data.form-default.password=${test.credentials.valid.password}
data.form-default.expectedMessage=${project.message.authenticated-welcome}

data.login-default.route=${project.route.login}
data.login-default.expectedRouteFragment=${project.route.authenticated}
data.login-default.username=${test.credentials.valid.username}
data.login-default.password=${test.credentials.valid.password}
data.login-default.expectedMessage=${project.message.authenticated-welcome}
