package ua.demo.agentlab.ai.rag.retrieval;

public enum RagTaskType {
    UI_TEST_GENERATION,
    API_TEST_GENERATION,
    NEGATIVE_TEST_GENERATION,
    SMOKE_TEST_GENERATION,
    REGRESSION_TEST_GENERATION,
    PAGE_OBJECT_GENERATION,
    FAILURE_ANALYSIS,
    BUG_FIX,
    CODE_REVIEW,
    GENERAL_AUTOMATION
}
