package ua.demo.agentlab.artifactreuse.policy;

public enum ArtifactInvalidationReason {
    NO_ISSUE,
    REUSE_DISABLED,
    FORCE_REFRESH,
    FINGERPRINT_CHANGED,
    SCHEMA_CHANGED,
    PROMPT_TEMPLATE_CHANGED,
    WRITER_VERSION_CHANGED,
    QUALITY_GATE_FAILED,
    COMPILE_FAILED,
    SMOKE_FAILED,
    PAGE_FINGERPRINT_CHANGED,
    REQUIRED_ACTIONS_CHANGED,
    REQUIRED_ASSERTIONS_CHANGED
}
