package ua.demo.agentlab.ui.contract;

public enum AssertionIntentKind {

    PAGE_VISIBLE,
    PAGE_ACCESSIBLE,
    CONTENT_VISIBLE,
    COLLECTION_VISIBLE,
    ENTITY_SUMMARY_VISIBLE,
    ENTITY_CONTENT_VISIBLE,
    DETAILS_VISIBLE,
    ENTITY_PRESENT_IN_CONTAINER,
    PUBLIC_ACCESSIBLE,
    LISTING_VISIBLE,
    ITEM_CARDS_VISIBLE,
    ITEM_CONTENT_VISIBLE,
    NON_EMPTY_RESULTS,
    DETAILS_OPENED,
    ITEM_PRESENT_IN_CONTAINER,
    CONTAINER_EMPTY,
    SUCCESS_STATE_VISIBLE,
    ERROR_VISIBLE,
    AUTH_REQUIRED,
    URL_CONTAINS
}
