package ua.demo.agentlab.artifactreuse.flow;

public enum FlowState {
    UNAUTHENTICATED,
    AUTHENTICATED,
    NAVIGATION_READY,
    NAVIGATION_COMPLETE,
    FORM_READY,
    FORM_DIRTY,
    FORM_SUBMITTED,
    RECORD_LIST_VISIBLE,
    RECORD_DETAILS_VISIBLE,
    MODAL_OPEN,
    USER_MENU_OPEN,
    FILTER_APPLIED,
    SORT_APPLIED,
    PAGE_CHANGED,
    FILE_SELECTED,
    DOWNLOAD_REQUESTED,
    CONTAINER_UPDATED
}
